<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Caroline Campbell" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 1: COVID-19 Trends</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project1/">Project 1: COVID-19 Trends</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         April 4, 2021 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              
<script src="../../rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="../../rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="../../rmarkdown-libs/htmlwidgets/htmlwidgets.js"></script>
<script src="../../rmarkdown-libs/plotly-binding/plotly.js"></script>
<script src="../../rmarkdown-libs/typedarray/typedarray.min.js"></script>
<script src="../../rmarkdown-libs/jquery/jquery.min.js"></script>
<link href="../../rmarkdown-libs/crosstalk/css/crosstalk.css" rel="stylesheet" />
<script src="../../rmarkdown-libs/crosstalk/js/crosstalk.min.js"></script>
<link href="../../rmarkdown-libs/plotly-htmlwidgets-css/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="../../rmarkdown-libs/plotly-main/plotly-latest.min.js"></script>


<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>The following information illustrates data between two datasets. One dataset is based off of the number of COVID-19 cases and fatalities in Texas counties, and the other dataset contains information about the number of COVID vaccine doses administered in all of the counties in Texas based on different age groups. Both datasets were up-to-date for each county as of March 22, 2021. For the case count data, the variables include: County, Confirmed Cases, and Fatalities. The vaccine distribution data includes variables such as County Name, Age Group, and Doses Administered. Both datasets were individually acquired from the Texas Department of State Health Services.</p>
<p>The topic of COVID-19 cases and vaccine distribution is interesting to me because of the current relevance of the information. Because this month, March, marks a year since the SARS-CoV-2 virus reached Texas, I was compelled to see the current state of different counties in Texas. I hypothesize that counties that have vaccinated more people will have less COVID-19 cases and less fatalities. I expect this association based on the fact that some of the vaccines, such as Moderna and Pfizer, have an efficacy rate of approximately 95%, which leads me to believe that there will be less cases after more of the population has been vaccinated.</p>
</div>
<div id="tidying-rearranging-widelong" class="section level2">
<h2>Tidying: Rearranging Wide/Long</h2>
<pre class="r"><code>library(tidyverse)
covidcases &lt;- read_csv(&quot;covidcases.csv&quot;)
covidvaccine &lt;- read_csv(&quot;covidvaccine.csv&quot;)
# renaming to replace spaces in column title with an
# underscore
names(covidcases) &lt;- gsub(&quot;\\s&quot;, &quot;_&quot;, names(covidcases))
head(covidcases)</code></pre>
<pre><code>## # A tibble: 6 x 3
##   County    Confirmed_Cases Fatalities
##   &lt;chr&gt;               &lt;dbl&gt;      &lt;dbl&gt;
## 1 Anderson             4790        112
## 2 Andrews              1710         47
## 3 Angelina             4706        268
## 4 Aransas               893         35
## 5 Archer                680         12
## 6 Armstrong             109          6</code></pre>
<pre class="r"><code># Making `covidcases` wide then long
longcovidcases &lt;- covidcases %&gt;% rename(Cases = Confirmed_Cases) %&gt;% 
    distinct() %&gt;% pivot_wider(names_from = &quot;County&quot;, values_from = &quot;Cases&quot;) %&gt;% 
    pivot_longer(cols = c(-Fatalities), names_to = &quot;County&quot;, 
        values_to = &quot;Cases&quot;, values_drop_na = TRUE) %&gt;% mutate(County = str_replace(County, 
    &quot;Unknown&quot;, &quot;Other&quot;)) %&gt;% select(County, Cases, Fatalities) %&gt;% 
    arrange(-desc(County))
head(longcovidcases)</code></pre>
<pre><code>## # A tibble: 6 x 3
##   County    Cases Fatalities
##   &lt;chr&gt;     &lt;dbl&gt;      &lt;dbl&gt;
## 1 Anderson   4790        112
## 2 Andrews    1710         47
## 3 Angelina   4706        268
## 4 Aransas     893         35
## 5 Archer      680         12
## 6 Armstrong   109          6</code></pre>
<pre class="r"><code># renaming to replace &#39;.&#39; in column title with an underscore
names(covidvaccine) &lt;- gsub(&quot;\\s&quot;, &quot;_&quot;, names(covidvaccine))
head(covidvaccine)</code></pre>
<pre><code>## # A tibble: 6 x 3
##   County_Name Age_Group   Doses_Administered
##   &lt;chr&gt;       &lt;chr&gt;                    &lt;dbl&gt;
## 1 Anderson    16-49 years               1413
## 2 Anderson    50-64 years               2042
## 3 Anderson    65-79 years               3472
## 4 Anderson    80+ years                 1009
## 5 Anderson    Unknown                      2
## 6 Andrews     16-49 years               3288</code></pre>
<pre class="r"><code># Making `covidvaccine` wide then long
longcovidvaccine &lt;- covidvaccine %&gt;% rename(County = County_Name) %&gt;% 
    distinct() %&gt;% pivot_wider(names_from = &quot;Age_Group&quot;, values_from = &quot;Doses_Administered&quot;) %&gt;% 
    pivot_longer(cols = c(-County), names_to = &quot;Age_Group&quot;, values_to = &quot;Vaccinated&quot;)
head(longcovidvaccine)</code></pre>
<pre><code>## # A tibble: 6 x 3
##   County   Age_Group   Vaccinated
##   &lt;chr&gt;    &lt;chr&gt;            &lt;dbl&gt;
## 1 Anderson 16-49 years       1413
## 2 Anderson 50-64 years       2042
## 3 Anderson 65-79 years       3472
## 4 Anderson 80+ years         1009
## 5 Anderson Unknown              2
## 6 Anderson Total               NA</code></pre>
<p>First, I replaced the space with an underscore in all of the column titles in both datasets to help run code throughout the rest of the project. Both datasets <code>covidcases</code> and <code>covidvaccine</code> were long to start with, so I used <code>pivot_wider()</code> to demonstrate the use of the function. I then returned the datasets to their long format using <code>pivot_longer</code>. I also made a new name for the long data, so I will be able to use it for the rest of the project. For <code>covidcases</code> I used <code>mutate()</code> and <code>str_replace()</code> to modify the “Unknown” counties to “Other” to match the <code>covidvaccine</code> dataset, which will help with joining in the next step.</p>
</div>
<div id="joiningmerging" class="section level2">
<h2>Joining/Merging</h2>
<pre class="r"><code>longcovidcases %&gt;% full_join(longcovidvaccine, by = &quot;County&quot;) %&gt;% 
    nrow()</code></pre>
<pre><code>## [1] 1800</code></pre>
<pre class="r"><code># Left join
covidjoined &lt;- longcovidcases %&gt;% left_join(longcovidvaccine, 
    by = &quot;County&quot;)
head(covidjoined)</code></pre>
<pre><code>## # A tibble: 6 x 5
##   County   Cases Fatalities Age_Group   Vaccinated
##   &lt;chr&gt;    &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;
## 1 Anderson  4790        112 16-49 years       1413
## 2 Anderson  4790        112 50-64 years       2042
## 3 Anderson  4790        112 65-79 years       3472
## 4 Anderson  4790        112 80+ years         1009
## 5 Anderson  4790        112 Unknown              2
## 6 Anderson  4790        112 Total               NA</code></pre>
<pre class="r"><code>nrow(covidjoined)</code></pre>
<pre><code>## [1] 1786</code></pre>
<pre class="r"><code>nrow(longcovidcases)</code></pre>
<pre><code>## [1] 256</code></pre>
<pre class="r"><code>nrow(longcovidvaccine)</code></pre>
<pre><code>## [1] 1799</code></pre>
<pre class="r"><code>1800 - 1786</code></pre>
<pre><code>## [1] 14</code></pre>
<pre class="r"><code>(14/1800) * 100</code></pre>
<pre><code>## [1] 0.7777778</code></pre>
<pre class="r"><code>countNA &lt;- function(z) sum(is.na(z))
covidjoined %&gt;% summarize_all(countNA)</code></pre>
<pre><code>## # A tibble: 1 x 5
##   County Cases Fatalities Age_Group Vaccinated
##    &lt;int&gt; &lt;int&gt;      &lt;int&gt;     &lt;int&gt;      &lt;int&gt;
## 1      0     0          0         1        565</code></pre>
<pre class="r"><code>nna_covidjoined &lt;- covidjoined %&gt;% na.omit()
nrow(covidjoined) - nrow(nna_covidjoined)</code></pre>
<pre><code>## [1] 565</code></pre>
<p>The data for <code>longcovidcases</code> had 256 observations, and <code>longcovidvaccine</code> had 1799 observations. I decided on a left join because I felt that it would be most effective to find the relationship between cases and vaccinations between the counties (i.e., the ID variable). All counties have COVID cases, but not all counties have the same capacity to carry out vaccinations. A left join with <code>longcovidcases</code> as the first dataframe would ensure that all counties are accounted for and not dropped. When I compared the number of observations in a full join (1,800) to the number of observations in the left join (1,786), there were only 14 observations that were lost. Less than 1% of observations were lost in the join (0.78%), so completing a left join still allows me to see the association later on in the project. If problems with finding an association were to occur, they would be minor. After finding how many NAs were present, there were relatively consistent numbers of NAs (0) across most variables, except for the <code>Vaccinated</code>, which had 565 NAs, so I decided to drop those values. There ended up being 565 observations dropped because of the numerous NAs in the <code>Vaccinated</code> category. Because I omitted the NA values, more data was lost. However, there should still be enough data left to find a relationship.</p>
</div>
<div id="wrangling" class="section level2">
<h2>Wrangling</h2>
<div id="six-core-dplyr-functions" class="section level3">
<h3>Six Core <code>dplyr</code> Functions</h3>
<pre class="r"><code># What county has the highest cases (besides the total number
# of cases)? (Using `filter()` and `select()`)
nna_covidjoined %&gt;% filter(Cases == max(Cases)) %&gt;% select(County, 
    Cases) %&gt;% distinct()</code></pre>
<pre><code>## # A tibble: 1 x 2
##   County  Cases
##   &lt;chr&gt;   &lt;dbl&gt;
## 1 Harris 369892</code></pre>
<pre class="r"><code># What county and age group has the most vaccinations? (Using
# `select()` and `arrange()`)
nna_covidjoined %&gt;% select(County, Age_Group, Vaccinated) %&gt;% 
    arrange(desc(Vaccinated)) %&gt;% distinct() %&gt;% head()</code></pre>
<pre><code>## # A tibble: 6 x 3
##   County Age_Group   Vaccinated
##   &lt;chr&gt;  &lt;chr&gt;            &lt;dbl&gt;
## 1 Harris 16-49 years     501123
## 2 Harris 65-79 years     418530
## 3 Harris 50-64 years     390344
## 4 Dallas 16-49 years     275185
## 5 Bexar  16-49 years     248774
## 6 Dallas 65-79 years     225423</code></pre>
<pre class="r"><code># What is the absolute difference between the number of
# `Cases` and number of `Fatalities`? (Using `mutate()`)
nna_covidjoined %&gt;% mutate(difference = abs(Cases - Fatalities)) %&gt;% 
    arrange(desc(difference))</code></pre>
<pre><code>## # A tibble: 1,221 x 6
##    County  Cases Fatalities Age_Group   Vaccinated difference
##    &lt;chr&gt;   &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;      &lt;dbl&gt;
##  1 Harris 369892       5625 16-49 years     501123     364267
##  2 Harris 369892       5625 50-64 years     390344     364267
##  3 Harris 369892       5625 65-79 years     418530     364267
##  4 Harris 369892       5625 80+ years       107285     364267
##  5 Harris 369892       5625 Unknown            347     364267
##  6 Dallas 250531       3776 16-49 years     275185     246755
##  7 Dallas 250531       3776 50-64 years     209198     246755
##  8 Dallas 250531       3776 65-79 years     225423     246755
##  9 Dallas 250531       3776 80+ years        60547     246755
## 10 Dallas 250531       3776 Unknown            198     246755
## # … with 1,211 more rows</code></pre>
<pre class="r"><code># using `group_by()`, `summarize()`, and `select()`
nna_covidjoined %&gt;% group_by(County) %&gt;% summarize_all(n_distinct) %&gt;% 
    select(County, Age_Group)</code></pre>
<pre><code>## # A tibble: 255 x 2
##    County    Age_Group
##    &lt;chr&gt;         &lt;int&gt;
##  1 Anderson          5
##  2 Andrews           4
##  3 Angelina          5
##  4 Aransas           5
##  5 Archer            4
##  6 Armstrong         5
##  7 Atascosa          5
##  8 Austin            5
##  9 Bailey            5
## 10 Bandera           5
## # … with 245 more rows</code></pre>
</div>
<div id="usingsummarize-and-group_by" class="section level3">
<h3>Using<code>summarize()</code> and <code>group_by()</code></h3>
<pre class="r"><code>library(kableExtra)
# Numeric Variable: Summary of `Cases`
kable(nna_covidjoined %&gt;% summarize(mean_Cases = mean(Cases, 
    na.rm = T), cor_Cases_Vaccinations = cor(Cases, Vaccinated, 
    use = &quot;pair&quot;), sd_Cases = sd(Cases, na.rm = T), n = n(), 
    max_Cases = max(Cases, na.rm = T), min_Cases = min(Cases, 
        na.rm = T)) %&gt;% head()) %&gt;% kable_styling(bootstrap_options = c(&quot;striped&quot;, 
    &quot;hover&quot;, &quot;condensed&quot;))</code></pre>
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
mean_Cases
</th>
<th style="text-align:right;">
cor_Cases_Vaccinations
</th>
<th style="text-align:right;">
sd_Cases
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
max_Cases
</th>
<th style="text-align:right;">
min_Cases
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
9677.249
</td>
<td style="text-align:right;">
0.7785923
</td>
<td style="text-align:right;">
35281.97
</td>
<td style="text-align:right;">
1221
</td>
<td style="text-align:right;">
369892
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Summary of `Cases` grouped by `Age_Group`
kable(nna_covidjoined %&gt;% group_by(Age_Group) %&gt;% summarize(mean_Cases = mean(Cases, 
    na.rm = T), sd_Cases = sd(Cases, na.rm = T), n = n(), max_Cases = max(Cases, 
    na.rm = T), min_Cases = min(Cases, na.rm = T)) %&gt;% head()) %&gt;% 
    kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;hover&quot;, &quot;condensed&quot;))</code></pre>
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Age_Group
</th>
<th style="text-align:right;">
mean_Cases
</th>
<th style="text-align:right;">
sd_Cases
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
max_Cases
</th>
<th style="text-align:right;">
min_Cases
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
16-49 years
</td>
<td style="text-align:right;">
9287.145
</td>
<td style="text-align:right;">
34630.88
</td>
<td style="text-align:right;">
255
</td>
<td style="text-align:right;">
369892
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
50-64 years
</td>
<td style="text-align:right;">
9287.145
</td>
<td style="text-align:right;">
34630.88
</td>
<td style="text-align:right;">
255
</td>
<td style="text-align:right;">
369892
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
65-79 years
</td>
<td style="text-align:right;">
9287.145
</td>
<td style="text-align:right;">
34630.88
</td>
<td style="text-align:right;">
255
</td>
<td style="text-align:right;">
369892
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
80+ years
</td>
<td style="text-align:right;">
9323.689
</td>
<td style="text-align:right;">
34694.33
</td>
<td style="text-align:right;">
254
</td>
<td style="text-align:right;">
369892
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Unknown
</td>
<td style="text-align:right;">
11599.198
</td>
<td style="text-align:right;">
38593.61
</td>
<td style="text-align:right;">
202
</td>
<td style="text-align:right;">
369892
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Numeric Variable: Summary of `Vaccinated`
kable(nna_covidjoined %&gt;% summarize(mean_Vaccinated = mean(Vaccinated, 
    na.rm = T), sd_Vaccinated = sd(Vaccinated, na.rm = T), n = n(), 
    max_Vaccinated = max(Vaccinated, na.rm = T), min_Vaccinated = min(Vaccinated, 
        na.rm = T)) %&gt;% head()) %&gt;% kable_styling(bootstrap_options = c(&quot;striped&quot;, 
    &quot;hover&quot;, &quot;condensed&quot;))</code></pre>
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
mean_Vaccinated
</th>
<th style="text-align:right;">
sd_Vaccinated
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
max_Vaccinated
</th>
<th style="text-align:right;">
min_Vaccinated
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
7632.814
</td>
<td style="text-align:right;">
31875.09
</td>
<td style="text-align:right;">
1221
</td>
<td style="text-align:right;">
501123
</td>
<td style="text-align:right;">
1
</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Summary of `Vaccinated` grouped by `County`
kable(nna_covidjoined %&gt;% group_by(County) %&gt;% summarize(mean_Vaccinated = mean(Vaccinated, 
    na.rm = T), sd_Vaccinated = sd(Vaccinated, na.rm = T), n = n(), 
    max_Vaccinated = max(Vaccinated, na.rm = T), min_Vaccinated = min(Vaccinated, 
        na.rm = T)) %&gt;% head()) %&gt;% kable_styling(bootstrap_options = c(&quot;striped&quot;, 
    &quot;hover&quot;, &quot;condensed&quot;))</code></pre>
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
County
</th>
<th style="text-align:right;">
mean_Vaccinated
</th>
<th style="text-align:right;">
sd_Vaccinated
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
max_Vaccinated
</th>
<th style="text-align:right;">
min_Vaccinated
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Anderson
</td>
<td style="text-align:right;">
1587.60
</td>
<td style="text-align:right;">
1288.1026
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
3472
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Andrews
</td>
<td style="text-align:right;">
2001.00
</td>
<td style="text-align:right;">
1154.1121
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
3288
</td>
<td style="text-align:right;">
566
</td>
</tr>
<tr>
<td style="text-align:left;">
Angelina
</td>
<td style="text-align:right;">
4938.80
</td>
<td style="text-align:right;">
3540.8735
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
9186
</td>
<td style="text-align:right;">
14
</td>
</tr>
<tr>
<td style="text-align:left;">
Aransas
</td>
<td style="text-align:right;">
1856.20
</td>
<td style="text-align:right;">
1702.2076
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
4547
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Archer
</td>
<td style="text-align:right;">
864.75
</td>
<td style="text-align:right;">
377.1484
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
1302
</td>
<td style="text-align:right;">
396
</td>
</tr>
<tr>
<td style="text-align:left;">
Armstrong
</td>
<td style="text-align:right;">
155.40
</td>
<td style="text-align:right;">
125.1891
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
343
</td>
<td style="text-align:right;">
1
</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Numeric Variable: Summary of `Fatalities`
kable(nna_covidjoined %&gt;% summarize(mean_Fatalities = mean(Fatalities, 
    na.rm = T), sd_Fatalities = sd(Fatalities, na.rm = T), n = n(), 
    max_Fatalities = max(Fatalities, na.rm = T), min_Fatalities = min(Fatalities, 
        na.rm = T)) %&gt;% head()) %&gt;% kable_styling(bootstrap_options = c(&quot;striped&quot;, 
    &quot;hover&quot;, &quot;condensed&quot;))</code></pre>
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
mean_Fatalities
</th>
<th style="text-align:right;">
sd_Fatalities
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
max_Fatalities
</th>
<th style="text-align:right;">
min_Fatalities
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
189.4693
</td>
<td style="text-align:right;">
565.0604
</td>
<td style="text-align:right;">
1221
</td>
<td style="text-align:right;">
5625
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Summary of `Fatalities` grouped by `Age_Group`
kable(nna_covidjoined %&gt;% group_by(Age_Group) %&gt;% summarize(mean_Fatalities = mean(Fatalities, 
    na.rm = T), sd_Fatalities = sd(Fatalities, na.rm = T), n = n(), 
    max_Fatalities = max(Fatalities, na.rm = T), min_Fatalities = min(Fatalities, 
        na.rm = T)) %&gt;% head()) %&gt;% kable_styling(bootstrap_options = c(&quot;striped&quot;, 
    &quot;hover&quot;, &quot;condensed&quot;))</code></pre>
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Age_Group
</th>
<th style="text-align:right;">
mean_Fatalities
</th>
<th style="text-align:right;">
sd_Fatalities
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
max_Fatalities
</th>
<th style="text-align:right;">
min_Fatalities
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
16-49 years
</td>
<td style="text-align:right;">
182.2667
</td>
<td style="text-align:right;">
554.9116
</td>
<td style="text-align:right;">
255
</td>
<td style="text-align:right;">
5625
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
50-64 years
</td>
<td style="text-align:right;">
182.2667
</td>
<td style="text-align:right;">
554.9116
</td>
<td style="text-align:right;">
255
</td>
<td style="text-align:right;">
5625
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
65-79 years
</td>
<td style="text-align:right;">
182.2667
</td>
<td style="text-align:right;">
554.9116
</td>
<td style="text-align:right;">
255
</td>
<td style="text-align:right;">
5625
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
80+ years
</td>
<td style="text-align:right;">
182.9843
</td>
<td style="text-align:right;">
555.8887
</td>
<td style="text-align:right;">
254
</td>
<td style="text-align:right;">
5625
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Unknown
</td>
<td style="text-align:right;">
224.9010
</td>
<td style="text-align:right;">
616.5764
</td>
<td style="text-align:right;">
202
</td>
<td style="text-align:right;">
5625
</td>
<td style="text-align:right;">
1
</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Categorical Variables
kable(nna_covidjoined %&gt;% group_by(County, Age_Group) %&gt;% summarize(mean_Vaccinated = mean(Vaccinated, 
    na.rm = T), n_distinct_Vaccinated = n_distinct(Vaccinated, 
    na.rm = T), n = n(), max_Vaccinated = max(Vaccinated, na.rm = T), 
    min_Vaccinated = min(Vaccinated, na.rm = T)) %&gt;% head()) %&gt;% 
    kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;hover&quot;, &quot;condensed&quot;))</code></pre>
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
County
</th>
<th style="text-align:left;">
Age_Group
</th>
<th style="text-align:right;">
mean_Vaccinated
</th>
<th style="text-align:right;">
n_distinct_Vaccinated
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
max_Vaccinated
</th>
<th style="text-align:right;">
min_Vaccinated
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Anderson
</td>
<td style="text-align:left;">
16-49 years
</td>
<td style="text-align:right;">
1413
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1413
</td>
<td style="text-align:right;">
1413
</td>
</tr>
<tr>
<td style="text-align:left;">
Anderson
</td>
<td style="text-align:left;">
50-64 years
</td>
<td style="text-align:right;">
2042
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2042
</td>
<td style="text-align:right;">
2042
</td>
</tr>
<tr>
<td style="text-align:left;">
Anderson
</td>
<td style="text-align:left;">
65-79 years
</td>
<td style="text-align:right;">
3472
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3472
</td>
<td style="text-align:right;">
3472
</td>
</tr>
<tr>
<td style="text-align:left;">
Anderson
</td>
<td style="text-align:left;">
80+ years
</td>
<td style="text-align:right;">
1009
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1009
</td>
<td style="text-align:right;">
1009
</td>
</tr>
<tr>
<td style="text-align:left;">
Anderson
</td>
<td style="text-align:left;">
Unknown
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Andrews
</td>
<td style="text-align:left;">
16-49 years
</td>
<td style="text-align:right;">
3288
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3288
</td>
<td style="text-align:right;">
3288
</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Correlation between `Cases` and `People`
covidjoined %&gt;% summarize(cor(Cases, Vaccinated, use = &quot;pair&quot;))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `cor(Cases, Vaccinated, use = &quot;pair&quot;)`
##                                    &lt;dbl&gt;
## 1                                  0.779</code></pre>
<p>Harris county had the most cases out of all of the counties with 369,892 COVID-19 cases and the most vaccinations with 501,123 vaccines distributed to the 16–49-year-old group. These statistics were generated using the <code>filter()</code> and <code>select()</code> functions. By utilizing the <code>mutate()</code> function, I was able to create another column based on the absolute differences between the number of <code>Cases</code> and <code>Fatalities</code>. Lastly, I used <code>group_by()</code>, <code>summarize_all()</code>, and <code>select()</code> to find the number of different ages groups per county.</p>
<p>For each of the numerical variables (<code>Cases</code>, <code>Vaccinations</code>, and <code>Fatalities</code>), I performed two summaries. First, I would summarize by the mean, standard deviation, count, max, and min. Then, I did the same statistics again after I grouped by either categorical variable <code>Age_Group</code> or <code>County</code>. To give the tables a better aesthetic, I used the <code>kable</code> package. Lastly, after grouping by the two categorical variables (<code>County</code> and <code>Age_Group</code>), I ran the same summary statistics for the <code>Vaccinated</code> variable. It was interesting to find out that the average number of people vaccinated was around 7,632, which was greater than the average number of fatalities (189).</p>
</div>
</div>
<div id="visualizing" class="section level2">
<h2>Visualizing</h2>
<div id="correlation-heat-map" class="section level3">
<h3>Correlation Heat Map</h3>
<pre class="r"><code>cor_cv &lt;- covidjoined %&gt;% select_if(is.numeric) %&gt;% cor(use = &quot;pair&quot;)
head(cor_cv)</code></pre>
<pre><code>##                Cases Fatalities Vaccinated
## Cases      1.0000000  0.9889732  0.7785923
## Fatalities 0.9889732  1.0000000  0.7572566
## Vaccinated 0.7785923  0.7572566  1.0000000</code></pre>
<pre class="r"><code>tidycor_cv &lt;- cor_cv %&gt;% as.data.frame %&gt;% rownames_to_column(&quot;var1&quot;) %&gt;% 
    pivot_longer(-1, names_to = &quot;var2&quot;, values_to = &quot;correlation&quot;)
tidycor_cv</code></pre>
<pre><code>## # A tibble: 9 x 3
##   var1       var2       correlation
##   &lt;chr&gt;      &lt;chr&gt;            &lt;dbl&gt;
## 1 Cases      Cases            1    
## 2 Cases      Fatalities       0.989
## 3 Cases      Vaccinated       0.779
## 4 Fatalities Cases            0.989
## 5 Fatalities Fatalities       1    
## 6 Fatalities Vaccinated       0.757
## 7 Vaccinated Cases            0.779
## 8 Vaccinated Fatalities       0.757
## 9 Vaccinated Vaccinated       1</code></pre>
<pre class="r"><code>tidycor_cv %&gt;% ggplot(aes(var1, var2, fill = correlation)) + 
    geom_tile() + scale_fill_gradient2(low = &quot;red&quot;, mid = &quot;white&quot;, 
    high = &quot;blue&quot;) + geom_text(aes(label = round(correlation, 
    2)), color = &quot;white&quot;, size = 4) + theme(axis.text.x = element_text(angle = 45, 
    hjust = 1)) + coord_fixed() + ggtitle(&quot;Correlation Between Cases, Fatalities, and Vaccinations&quot;) + 
    theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-5-1.png" width="672" style="display: block; margin: auto;" />
<em>Figure 1:</em> This is a correlation heat map between all of the numeric variables (<code>Cases</code>, <code>Fatalities</code>, and <code>Vaccinated</code>). It appears that there is a high correlation between all of the variables. The highest correlation, besides the 1.00 correlation with itself, is between <code>Fatalities</code> and <code>Cases</code>, with a correlation of 0.99. The lowest correlation is between <code>Vaccinated</code> and <code>Fatalities</code>, with a correlation of 0.76.</p>
</div>
<div id="two-ggplots" class="section level3">
<h3>Two ggplots</h3>
<pre class="r"><code># Number of Counties
nna_covidjoined %&gt;% summarize(n_distinct(County))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `n_distinct(County)`
##                  &lt;int&gt;
## 1                  255</code></pre>
<pre class="r"><code># Average Number of Cases &amp; Fatalities
nna_covidjoined %&gt;% summarize(mean(Cases), mean(Fatalities))</code></pre>
<pre><code>## # A tibble: 1 x 2
##   `mean(Cases)` `mean(Fatalities)`
##           &lt;dbl&gt;              &lt;dbl&gt;
## 1         9677.               189.</code></pre>
<pre class="r"><code># Relationship between `Cases` and `Fatalities` based on
# `County`
ggplot(nna_covidjoined, aes(Cases, Fatalities, color = County)) + 
    geom_point(stat = &quot;summary&quot;, fun = mean, shape = &quot;circle&quot;, 
        size = 1.5) + geom_point(aes(x = (mean(Cases)), y = (mean(Fatalities))), 
    color = &quot;red&quot;, shape = &quot;diamond&quot;, size = 6) + ggtitle(&quot;Number of Fatalities Against the Number of Cases by County&quot;) + 
    theme(plot.title = element_text(hjust = 0.5)) + xlab(&quot;Number of Cases (log scale)&quot;) + 
    ylab(&quot;Number of Fatalities (log scale)&quot;) + scale_x_log10() + 
    scale_y_log10() + theme(axis.text.x = element_text(angle = 45, 
    hjust = 1), legend.position = &quot;none&quot;)</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-6-1.png" width="672" style="display: block; margin: auto;" />
<em>Figure 2:</em> There is a positive correlation between the number of COVID-19 cases and the number of fatalities caused by the virus based on the county. This makes sense, as we would expect that some of the more populated counties would have more people. Therefore, there is more opportunity for the virus to spread and cause death. The legend for <code>County</code> coloration was removed because there are a total of 255 counties. Lastly, the red diamond plotted on top of the scatterplot represents the average number of cases (189) and fatalties (9,677) of all the counties.</p>
<pre class="r"><code># Relationship between Number of `Vaccinations` and
# `Age_Group` between `County`
ggplot(nna_covidjoined, aes(x = Age_Group, y = Vaccinated, fill = County)) + 
    geom_bar(stat = &quot;summary&quot;, fun = mean) + ggtitle(&quot;Number of Vaccinations based on Age Group by County&quot;) + 
    theme(plot.title = element_text(hjust = 0.5)) + xlab(&quot;Age Group&quot;) + 
    scale_y_log10() + scale_y_continuous(name = &quot;Number of Vaccinations (log scale)&quot;, 
    breaks = seq(0, 3e+06, 3e+05)) + theme(axis.text.x = element_text(angle = 45, 
    hjust = 1), legend.position = &quot;none&quot;)</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-7-1.png" width="672" style="display: block; margin: auto;" />
<em>Figure 3:</em> As illustrated above, there is an apparent trend that the 16-49 year-old age group results in the greatest number of COVD-19 vaccinations. The next age group that had the highest number of vaccinations was the 65-79 year-old age group, then 50-64, and lastly the 80+ years. The legend for the <code>County</code> coloration was too large, so it needed to be removed. However, the counties in the pink region had the least number of vaccinations, and the red/orange region had the most.</p>
</div>
</div>
<div id="dimensionality-reduction" class="section level2">
<h2>Dimensionality Reduction</h2>
<pre class="r"><code>library(cluster)
# scaling data
pam_dat &lt;- nna_covidjoined %&gt;% select(-Age_Group, -County) %&gt;% 
    scale
# finding number of clusters
sil_width &lt;- vector()
for (i in 2:10) {
    pam_fit &lt;- pam(pam_dat, k = i)
    sil_width[i] &lt;- pam_fit$silinfo$avg.width
}
ggplot() + geom_line(aes(x = 1:10, y = sil_width)) + scale_x_continuous(name = &quot;k&quot;, 
    breaks = 1:10)  #2 clusters is best</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-8-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code># running PAM using numeric variables
pam2 &lt;- nna_covidjoined %&gt;% select(-Age_Group, -County) %&gt;% scale %&gt;% 
    pam(2)
pam2</code></pre>
<pre><code>## Medoids:
##        ID      Cases Fatalities Vaccinated
## [1,]  792 -0.2357365 -0.2556705 -0.2032877
## [2,] 1052  5.6946576  4.6924727  5.0076145
## Clustering vector:
##   [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
##  [38] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 1
##  [75] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
##  [ reached getOption(&quot;max.print&quot;) -- omitted 1121 entries ]
## Objective function:
##     build      swap 
## 0.3695177 0.3695177 
## 
## Available components:
##  [1] &quot;medoids&quot;    &quot;id.med&quot;     &quot;clustering&quot; &quot;objective&quot;  &quot;isolation&quot; 
##  [6] &quot;clusinfo&quot;   &quot;silinfo&quot;    &quot;diss&quot;       &quot;call&quot;       &quot;data&quot;</code></pre>
<pre class="r"><code># visualize
final &lt;- nna_covidjoined %&gt;% mutate(cluster = pam2$clustering)
library(plotly)
final %&gt;% plot_ly(x = ~Cases, y = ~Fatalities, z = ~Vaccinated, 
    color = ~cluster, type = &quot;scatter3d&quot;, mode = &quot;markers&quot;) %&gt;% 
    layout(autosize = F, width = 900, height = 400)</code></pre>
<div id="htmlwidget-1" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-1">{"x":{"visdat":{"67e826bd2445":["function () ","plotlyVisDat"]},"cur_data":"67e826bd2445","attrs":{"67e826bd2445":{"x":{},"y":{},"z":{},"mode":"markers","color":{},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter3d"}},"layout":{"width":900,"height":400,"margin":{"b":40,"l":60,"t":25,"r":10},"autosize":false,"scene":{"xaxis":{"title":"Cases"},"yaxis":{"title":"Fatalities"},"zaxis":{"title":"Vaccinated"}},"hovermode":"closest","showlegend":false,"legend":{"yanchor":"top","y":0.5}},"source":"A","config":{"showSendToCloud":false},"data":[{"x":[4790,4790,4790,4790,4790,1710,1710,1710,1710,4706,4706,4706,4706,4706,893,893,893,893,893,680,680,680,680,109,109,109,109,109,4136,4136,4136,4136,4136,1645,1645,1645,1645,1645,594,594,594,594,594,935,935,935,935,935,6710,6710,6710,6710,6710,122,122,122,122,122,3077,3077,3077,3077,3077,21260,21260,21260,21260,21260,171335,171335,171335,171335,171335,577,577,577,577,577,21,21,21,21,1329,1329,1329,1329,1329,4643,4643,4643,4643,4643,29114,29114,29114,29114,29114,18617,18617,18617,18617,18617,821,821,821,821,821,77,77,77,77,657,657,657,657,1963,1963,1963,1963,1963,1869,1869,1869,1869,1869,3947,3947,3947,3947,3947,5020,5020,5020,5020,5020,1692,1692,1692,1692,1692,592,592,592,592,38122,38122,38122,38122,38122,804,804,804,804,804,257,257,257,257,257,1141,1141,1141,1141,1141,655,655,655,655,655,4515,4515,4515,4515,4515,2244,2244,2244,2244,2244,1315,1315,1315,1315,1315,927,927,927,927,927,227,227,227,227,227,219,219,219,219,482,482,482,482,482,71525,71525,71525,71525,71525,199,199,199,199,199,1330,1330,1330,1330,1330,5025,5025,5025,5025,5025,1159,1159,1159,1159,1159,227,227,227,227,3101,3101,3101,3101,3101,6717,6717,6717,6717,6717,143,143,143,143,201,201,201,201,217,217,217,217,319,319,319,319,329,329,329,329,792,792,792,792,792,250531,250531,250531,250531,250531,1716,1716,1716,1716,1716,2000,2000,2000,2000,2000,175,175,175,175,52722,52722,52722,52722,52722,1897,1897,1897,1897,1897,100,100,100,100,100,1402,1402,1402,1402,1402,174,174,174,174,174,1074,1074,1074,1074,1074,924,924,924,924,924,8507,8507,8507,8507,8507,199,199,199,199,199,128119,128119,128119,128119,128119,18304,18304,18304,18304,18304,2747,2747,2747,2747,2747,1853,1853,1853,1853,1853,2560,2560,2560,2560,2560,1494,1494,1494,1494,1494,290,290,290,290,323,323,323,323,323,87,87,87,87,53759,53759,53759,53759,53759,494,494,494,494,494,1056,1056,1056,1056,1056,2138,2138,2138,2138,2138,1416,1416,1416,1416,1416,31337,31337,31337,31337,31337,219,219,219,219,1666,1666,1666,1666,1666,39,39,39,39,39,279,279,279,279,279,2320,2320,2320,2320,1724,1724,1724,1724,1724,10979,10979,10979,10979,10979,5980,5980,5980,5980,5980,3182,3182,3182,3182,3182,10352,10352,10352,10352,10352,6067,6067,6067,6067,326,326,326,326,326,703,703,703,703,369,369,369,369,311,311,311,311,311,2520,2520,2520,2520,2520,369892,369892,369892,369892,369892,2392,2392,2392,2392,2392,501,501,501,501,501,197,197,197,197,197,16877,16877,16877,16877,16877,503,503,503,503,503,3780,3780,3780,3780,3780,55595,55595,55595,55595,55595,3691,3691,3691,3691,3691,2087,2087,2087,2087,2087,4216,4216,4216,4216,4216,1552,1552,1552,1552,1552,874,874,874,874,874,2997,2997,2997,2997,2997,430,430,430,430,430,5498,5498,5498,5498,5498,1098,1098,1098,1098,1098,50,50,50,50,50,526,526,526,526,526,1465,1465,1465,1465,1465,937,937,937,937,937,147,147,147,147,147,18668,18668,18668,18668,18668,573,573,573,573,573,3566,3566,3566,3566,3566,16361,16361,16361,16361,16361,2050,2050,2050,2050,2050,1598,1598,1598,1598,1598,12946,12946,12946,12946,12946,1636,1636,1636,1636,1636,17,17,17,17,39,39,39,39,2198,2198,2198,2198,2198,208,208,208,208,5,5,5,324,324,324,324,324,1855,1855,1855,1855,1855,171,171,171,171,880,880,880,880,2620,2620,2620,2620,2620,1557,1557,1557,1557,1765,1765,1765,1765,1765,1892,1892,1892,1892,1892,979,979,979,979,979,1243,1243,1243,1243,1243,5621,5621,5621,5621,5621,2090,2090,2090,2090,2090,278,278,278,278,278,866,866,866,866,866,1119,1119,1119,1119,1119,1,1,1,1,48433,48433,48433,48433,48433,610,610,610,610,610,1682,1682,1682,1682,1682,340,340,340,340,363,363,363,363,363,246,246,246,246,2906,2906,2906,2906,2906,10295,10295,10295,10295,10295,401,401,401,401,401,25747,25747,25747,25747,25747,64,64,64,64,3703,3703,3703,3703,3703,143,143,143,143,16829,16829,16829,16829,16829,1360,1360,1360,1360,1360,589,589,589,589,593,593,593,593,1730,1730,1730,1730,39068,39068,39068,39068,39068,1960,1960,1960,1960,1960,569,569,569,569,569,36,36,36,36,3274,3274,3274,3274,3274,3401,3401,3401,3401,3401,284,284,284,284,1516,1516,1516,1516,1516,26155,26155,26155,26155,26155,936,936,936,936,936,117,117,117,117,3988,3988,3988,3988,3988,0,0,0,0,0,2450,2450,2450,2450,2450,964,964,964,964,964,12136,12136,12136,12136,12136,857,857,857,857,857,1282,1282,1282,1282,1282,1397,1397,1397,1397,1397,17079,17079,17079,17079,17079,639,639,639,639,639,393,393,393,393,393,16377,16377,16377,16377,16377,198,198,198,198,272,272,272,272,401,401,401,401,401,1003,1003,1003,1003,1003,570,570,570,570,570,56,56,56,56,1638,1638,1638,1638,1638,8952,8952,8952,8952,8952,773,773,773,773,773,2168,2168,2168,2168,2168,167,167,167,167,327,327,327,327,327,791,791,791,791,791,3165,3165,3165,3165,3165,544,544,544,544,544,121,121,121,121,2270,2270,2270,2270,2270,126,126,126,126,893,893,893,893,893,176,176,176,176,11197,11197,11197,11197,11197,583,583,583,583,583,7565,7565,7565,7565,7565,419,419,419,419,49,49,49,49,49,49,49,49,49,279,279,279,279,401,401,401,401,401,210596,210596,210596,210596,210596,7106,7106,7106,7106,7106,64,64,64,64,1682,1682,1682,1682,1682,50,50,50,50,2681,2681,2681,2681,2681,4604,4604,4604,4604,4604,78193,78193,78193,78193,78193,494,494,494,494,546,546,546,546,546,1311,1311,1311,1311,1311,71,71,71,71,3360,3360,3360,3360,3360,7763,7763,7763,7763,7763,2537,2537,2537,2537,2537,8050,8050,8050,8050,8050,7656,7656,7656,7656,7656,3228,3228,3228,3228,3228,682,682,682,682,682,3124,3124,3124,3124,3124,43003,43003,43003,43003,43003,3472,3472,3472,3472,3472,439,439,439,439,439,14742,14742,14742,14742,14742,1598,1598,1598,1598,1598,2352,2352,2352,2352,2352,36556,36556,36556,36556,36556,3164,3164,3164,3164,3164,554,554,554,554,554,5923,5923,5923,5923,5923,1918,1918,1918,1918,1918,863,863,863,863,863,1899,1899,1899,1899,1899,1549,1549,1549,1549,1549,1629,1629,1629,1629,1629],"y":[112,112,112,112,112,47,47,47,47,268,268,268,268,268,35,35,35,35,35,12,12,12,12,6,6,6,6,6,143,143,143,143,143,34,34,34,34,34,18,18,18,18,18,27,27,27,27,27,88,88,88,88,88,11,11,11,11,11,68,68,68,68,68,392,392,392,392,392,3218,3218,3218,3218,3218,19,19,19,19,19,2,2,2,2,33,33,33,33,33,198,198,198,198,198,429,429,429,429,429,231,231,231,231,231,12,12,12,12,12,5,5,5,5,36,36,36,36,116,116,116,116,116,38,38,38,38,38,61,61,61,61,61,92,92,92,92,92,20,20,20,20,20,38,38,38,38,1424,1424,1424,1424,1424,42,42,42,42,42,14,14,14,14,14,79,79,79,79,79,30,30,30,30,30,24,24,24,24,24,132,132,132,132,132,17,17,17,17,17,16,16,16,16,16,14,14,14,14,14,11,11,11,11,31,31,31,31,31,782,782,782,782,782,9,9,9,9,9,25,25,25,25,25,279,279,279,279,279,51,51,51,51,51,8,8,8,8,65,65,65,65,65,83,83,83,83,83,7,7,7,7,12,12,12,12,15,15,15,15,28,28,28,28,8,8,8,8,24,24,24,24,24,3776,3776,3776,3776,3776,68,68,68,68,68,64,64,64,64,64,11,11,11,11,709,709,709,709,709,58,58,58,58,58,10,10,10,10,10,28,28,28,28,28,15,15,15,15,15,39,39,39,39,39,47,47,47,47,47,349,349,349,349,349,4,4,4,4,4,2520,2520,2520,2520,2520,300,300,300,300,300,67,67,67,67,67,29,29,29,29,29,105,105,105,105,105,56,56,56,56,56,14,14,14,14,29,29,29,29,29,9,9,9,9,617,617,617,617,617,26,26,26,26,26,48,48,48,48,48,47,47,47,47,47,42,42,42,42,42,384,384,384,384,384,22,22,22,22,48,48,48,48,48,2,2,2,2,2,13,13,13,13,13,55,55,55,55,54,54,54,54,54,335,335,335,335,335,338,338,338,338,338,66,66,66,66,66,200,200,200,200,200,153,153,153,153,14,14,14,14,14,26,26,26,26,23,23,23,23,12,12,12,12,12,102,102,102,102,102,5625,5625,5625,5625,5625,102,102,102,102,102,2,2,2,2,2,26,26,26,26,26,200,200,200,200,200,2,2,2,2,2,174,174,174,174,174,2430,2430,2430,2430,2430,104,104,104,104,104,100,100,100,100,100,122,122,122,122,122,107,107,107,107,107,47,47,47,47,47,100,100,100,100,100,11,11,11,11,11,158,158,158,158,158,71,71,71,71,71,1,1,1,1,1,16,16,16,16,16,30,30,30,30,30,83,83,83,83,83,4,4,4,4,4,376,376,376,376,376,15,15,15,15,15,92,92,92,92,92,352,352,352,352,352,53,53,53,53,53,33,33,33,33,33,233,233,233,233,233,69,69,69,69,69,2,2,2,2,2,2,2,2,83,83,83,83,83,6,6,6,6,0,0,0,6,6,6,6,6,88,88,88,88,88,15,15,15,15,24,24,24,24,151,151,151,151,151,80,80,80,80,32,32,32,32,32,74,74,74,74,74,37,37,37,37,37,41,41,41,41,41,169,169,169,169,169,69,69,69,69,69,12,12,12,12,12,20,20,20,20,20,50,50,50,50,50,0,0,0,0,773,773,773,773,773,23,23,23,23,23,27,27,27,27,27,33,33,33,33,18,18,18,18,18,6,6,6,6,95,95,95,95,95,329,329,329,329,329,18,18,18,18,18,457,457,457,457,457,5,5,5,5,103,103,103,103,103,9,9,9,9,258,258,258,258,258,45,45,45,45,45,21,21,21,21,30,30,30,30,68,68,68,68,499,499,499,499,499,70,70,70,70,70,33,33,33,33,33,8,8,8,8,162,162,162,162,162,134,134,134,134,134,34,34,34,34,50,50,50,50,50,653,653,653,653,653,25,25,25,25,25,4,4,4,4,124,124,124,124,124,22,22,22,22,22,70,70,70,70,70,74,74,74,74,74,169,169,169,169,169,35,35,35,35,35,34,34,34,34,34,103,103,103,103,103,374,374,374,374,374,24,24,24,24,24,25,25,25,25,25,271,271,271,271,271,8,8,8,8,12,12,12,12,36,36,36,36,36,40,40,40,40,40,20,20,20,20,20,1,1,1,1,39,39,39,39,39,145,145,145,145,145,36,36,36,36,36,104,104,104,104,104,40,40,40,40,30,30,30,30,30,32,32,32,32,32,144,144,144,144,144,23,23,23,23,23,6,6,6,6,62,62,62,62,62,4,4,4,4,64,64,64,64,64,12,12,12,12,439,439,439,439,439,14,14,14,14,14,283,283,283,283,283,25,25,25,25,4,4,4,4,6,6,6,6,6,8,8,8,8,17,17,17,17,17,2841,2841,2841,2841,2841,386,386,386,386,386,2,2,2,2,54,54,54,54,54,5,5,5,5,83,83,83,83,83,265,265,265,265,265,933,933,933,933,933,23,23,23,23,36,36,36,36,36,67,67,67,67,67,9,9,9,9,68,68,68,68,68,211,211,211,211,211,112,112,112,112,112,192,192,192,192,192,122,122,122,122,122,45,45,45,45,45,21,21,21,21,21,86,86,86,86,86,750,750,750,750,750,110,110,110,110,110,10,10,10,10,10,367,367,367,367,367,55,55,55,55,55,84,84,84,84,84,438,438,438,438,438,65,65,65,65,65,21,21,21,21,21,115,115,115,115,115,121,121,121,121,121,27,27,27,27,27,43,43,43,43,43,30,30,30,30,30,40,40,40,40,40],"z":[1413,2042,3472,1009,2,3288,2442,1708,566,5590,6880,9186,3024,14,1162,2243,4547,1327,2,793,968,1302,396,142,186,343,105,1,3100,3297,3752,947,3,1957,2553,4746,1418,3,972,944,855,314,2,948,1614,3066,776,4,5531,5869,7228,1608,5,272,452,792,257,2,4052,4145,4003,1125,9,22463,17422,23020,7190,20,248774,173852,175262,43540,271,516,1011,2273,518,3,37,42,76,19,1026,1549,2771,966,1,4328,5039,6913,2489,10,41150,32979,37702,10045,20,22954,15151,18316,6207,25,1603,1459,1844,423,11,125,180,323,123,1098,1024,1054,353,1901,2397,3714,1131,6,845,1501,2354,721,4,1966,2772,6458,2351,3,2531,2492,3270,942,5,1277,1663,2168,749,5,771,1016,1460,484,58694,41511,48157,12500,126,545,676,1309,417,1,361,532,728,252,1,772,1364,2349,706,2,555,635,914,391,1,3051,3161,4344,992,18,2204,2811,4638,1413,13,715,599,752,298,3,860,1542,2188,624,2,419,412,318,104,4,139,315,508,211,349,546,984,349,1,132279,101541,109829,26723,164,180,282,403,172,3,996,1769,3458,1143,1,13768,14184,21993,5054,14,688,1165,2060,826,2,187,275,534,188,1658,2490,4607,1558,6,3279,3230,4434,1529,15,56,150,174,63,600,492,437,124,282,407,537,137,618,832,934,337,269,283,328,72,1623,779,597,241,3,275185,209198,225423,60547,198,505,744,1025,346,6,1260,1470,1569,571,4,215,277,639,210,95019,70995,86019,18546,29,857,1440,2129,672,4,90,166,322,109,1,2202,1749,1630,379,6,174,286,488,203,1,1654,1688,1642,499,6,1017,1320,1787,722,2,18379,14758,11420,3070,16,373,485,468,159,3,124240,84043,84512,28682,267,15505,15370,21142,5497,14,2523,2789,3938,1527,5,862,1230,1811,572,2,1587,2465,4067,1459,1,1069,1711,3839,1235,2,148,290,516,201,520,633,785,359,1,89,212,213,78,109789,83857,102404,20309,80,316,638,1261,478,1,548,970,1647,483,2,1701,1586,1634,455,1,945,892,816,317,2,40811,37182,45787,11809,28,264,374,485,174,1357,1918,5774,2205,7,264,214,165,60,1,430,710,1249,383,1,1442,1670,2260,915,1317,1398,1910,758,1,7275,8407,13050,4118,24,8586,9350,12908,4668,23,1352,1975,3174,821,3,14220,12117,14213,3567,21,2472,2625,2982,989,199,346,550,190,6,584,763,1303,603,382,504,653,286,478,451,726,200,1,3427,4245,6728,2130,21,501123,390344,418530,107285,347,2739,3903,5825,1727,6,1252,759,613,193,2,474,538,798,363,1,25446,17044,22265,5045,57,479,401,517,159,1,2756,4863,8939,2773,7,123508,71816,66844,17931,97,1692,2745,4505,1488,4,2167,2217,2382,772,2,3463,5331,10927,3542,14,1505,2113,3492,1352,6,886,1488,2453,874,2,2186,2095,2114,679,6,688,341,412,82,1,4268,5639,8562,2705,13,1265,1649,2182,653,2,84,195,228,67,1,495,652,926,438,10,957,1224,1987,692,3,1544,3057,5079,1629,6,350,471,637,126,2,16398,20209,22254,7358,44,977,767,766,292,1,6359,6194,5600,1419,13,11329,11512,14655,4068,23,804,1048,1610,544,1,944,1300,1648,608,4,9583,8311,10184,2539,13,4415,4946,7531,2231,3,87,110,63,18,44,58,115,82,3055,3173,6806,2360,2,214,387,871,289,17,21,15,227,224,459,179,2,7231,4984,4505,1156,13,319,447,512,287,1624,1251,1029,255,2908,4302,6388,2317,9,1131,1472,1338,644,859,1179,1899,588,7,913,1432,2846,1064,8,837,1100,1706,597,3,405,787,1785,544,2,2602,3673,6007,1593,5,874,1281,2097,575,2,190,270,371,158,3,687,1026,1356,386,6,610,1270,3719,1430,1,11,18,6,3,46782,34295,35436,10638,43,581,652,547,234,1,373,600,1027,408,1,354,578,911,350,649,574,489,161,1,214,345,829,387,1860,2220,3242,867,10,6632,3829,2997,723,4,289,563,1125,376,1,19889,17923,25051,7982,56,41,89,117,46,3974,4426,5635,1486,4,179,255,504,157,15887,11955,12140,3766,16,1153,1785,3198,1005,9,280,374,821,335,399,560,725,254,856,1414,2840,894,40558,34546,60521,14408,30,3708,2742,2093,570,6,395,630,1139,442,3,58,90,223,100,4772,5462,7364,2100,8,3821,5257,7035,1912,5,427,900,1409,409,895,1236,2030,705,2,43049,36772,40238,9842,50,1155,751,800,261,5,127,189,203,85,3443,4897,7403,2308,9,153516,124517,95566,43236,99,1049,1640,3022,857,8,635,975,2027,725,3,10080,10571,15879,4258,12,1081,1124,982,410,2,3275,2308,1812,563,5,1703,3116,6638,2073,9,11112,11670,12154,4269,29,1984,1561,1597,469,2,307,594,1366,357,1,17022,15925,19012,5393,27,363,332,292,63,157,327,937,237,454,925,1797,548,1,2546,2293,1838,516,4,565,894,1136,391,1,40,50,122,30,681,1189,2038,634,3,10545,9669,11911,2771,8,700,910,1438,521,1,1699,2776,4519,1434,3,276,866,1820,633,347,782,1353,522,7,725,1539,3090,876,5,5777,6214,7240,1711,10,123,216,539,184,1,226,271,475,122,1261,1473,1807,746,7,156,281,424,144,676,1162,1853,739,5,373,328,277,98,16924,17242,25218,8843,19,623,813,1322,359,1,12206,7346,6369,1706,17,445,552,934,374,73,125,138,45,86,124,252,124,1,245,350,565,155,485,638,909,372,6,196547,167251,184150,47966,189,16052,13122,15161,5472,16,124,165,184,53,1393,1506,1385,466,1,182,222,256,160,1328,1573,2300,833,6,11338,11571,16214,5755,4,185766,94396,96578,20608,186,555,1067,2120,718,628,1308,2807,921,3,1561,2246,3455,1114,3,668,498,399,126,3296,3086,3989,1301,3,4235,3303,4625,1452,4,1929,2971,5351,1945,2,6251,6885,9923,3375,19,3409,3701,5360,1674,5,2322,2740,4287,1022,1,1389,1287,1253,382,5,1853,2688,5969,2109,3,50008,31324,23209,5604,104,2103,2650,3887,1227,9,335,452,710,251,3,10014,11048,14944,5130,15,1762,1587,2053,605,6,2657,2149,2081,609,10,67244,40953,47759,12700,85,3896,4316,4623,1116,6,815,930,741,211,1,3283,4229,6896,1949,3,1234,2519,6418,2123,5,802,775,696,223,1,1186,1475,2392,853,4,2189,1367,1359,389,1,1922,1490,1356,327,3],"mode":"markers","type":"scatter3d","marker":{"colorbar":{"title":"cluster","ticklen":2},"cmin":1,"cmax":2,"colorscale":[["0","rgba(68,1,84,1)"],["0.0416666666666667","rgba(70,19,97,1)"],["0.0833333333333333","rgba(72,32,111,1)"],["0.125","rgba(71,45,122,1)"],["0.166666666666667","rgba(68,58,128,1)"],["0.208333333333333","rgba(64,70,135,1)"],["0.25","rgba(60,82,138,1)"],["0.291666666666667","rgba(56,93,140,1)"],["0.333333333333333","rgba(49,104,142,1)"],["0.375","rgba(46,114,142,1)"],["0.416666666666667","rgba(42,123,142,1)"],["0.458333333333333","rgba(38,133,141,1)"],["0.5","rgba(37,144,140,1)"],["0.541666666666667","rgba(33,154,138,1)"],["0.583333333333333","rgba(39,164,133,1)"],["0.625","rgba(47,174,127,1)"],["0.666666666666667","rgba(53,183,121,1)"],["0.708333333333333","rgba(79,191,110,1)"],["0.75","rgba(98,199,98,1)"],["0.791666666666667","rgba(119,207,85,1)"],["0.833333333333333","rgba(147,214,70,1)"],["0.875","rgba(172,220,52,1)"],["0.916666666666667","rgba(199,225,42,1)"],["0.958333333333333","rgba(226,228,40,1)"],["1","rgba(253,231,37,1)"]],"showscale":false,"color":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],"line":{"colorbar":{"title":"","ticklen":2},"cmin":1,"cmax":2,"colorscale":[["0","rgba(68,1,84,1)"],["0.0416666666666667","rgba(70,19,97,1)"],["0.0833333333333333","rgba(72,32,111,1)"],["0.125","rgba(71,45,122,1)"],["0.166666666666667","rgba(68,58,128,1)"],["0.208333333333333","rgba(64,70,135,1)"],["0.25","rgba(60,82,138,1)"],["0.291666666666667","rgba(56,93,140,1)"],["0.333333333333333","rgba(49,104,142,1)"],["0.375","rgba(46,114,142,1)"],["0.416666666666667","rgba(42,123,142,1)"],["0.458333333333333","rgba(38,133,141,1)"],["0.5","rgba(37,144,140,1)"],["0.541666666666667","rgba(33,154,138,1)"],["0.583333333333333","rgba(39,164,133,1)"],["0.625","rgba(47,174,127,1)"],["0.666666666666667","rgba(53,183,121,1)"],["0.708333333333333","rgba(79,191,110,1)"],["0.75","rgba(98,199,98,1)"],["0.791666666666667","rgba(119,207,85,1)"],["0.833333333333333","rgba(147,214,70,1)"],["0.875","rgba(172,220,52,1)"],["0.916666666666667","rgba(199,225,42,1)"],["0.958333333333333","rgba(226,228,40,1)"],["1","rgba(253,231,37,1)"]],"showscale":false,"color":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]}},"frame":null},{"x":[0,369892],"y":[0,5625],"type":"scatter3d","mode":"markers","opacity":0,"hoverinfo":"none","showlegend":false,"marker":{"colorbar":{"title":"cluster","ticklen":2,"len":0.5,"lenmode":"fraction","y":1,"yanchor":"top"},"cmin":1,"cmax":2,"colorscale":[["0","rgba(68,1,84,1)"],["0.0416666666666667","rgba(70,19,97,1)"],["0.0833333333333333","rgba(72,32,111,1)"],["0.125","rgba(71,45,122,1)"],["0.166666666666667","rgba(68,58,128,1)"],["0.208333333333333","rgba(64,70,135,1)"],["0.25","rgba(60,82,138,1)"],["0.291666666666667","rgba(56,93,140,1)"],["0.333333333333333","rgba(49,104,142,1)"],["0.375","rgba(46,114,142,1)"],["0.416666666666667","rgba(42,123,142,1)"],["0.458333333333333","rgba(38,133,141,1)"],["0.5","rgba(37,144,140,1)"],["0.541666666666667","rgba(33,154,138,1)"],["0.583333333333333","rgba(39,164,133,1)"],["0.625","rgba(47,174,127,1)"],["0.666666666666667","rgba(53,183,121,1)"],["0.708333333333333","rgba(79,191,110,1)"],["0.75","rgba(98,199,98,1)"],["0.791666666666667","rgba(119,207,85,1)"],["0.833333333333333","rgba(147,214,70,1)"],["0.875","rgba(172,220,52,1)"],["0.916666666666667","rgba(199,225,42,1)"],["0.958333333333333","rgba(226,228,40,1)"],["1","rgba(253,231,37,1)"]],"showscale":true,"color":[1,2],"line":{"color":"rgba(255,127,14,1)"}},"z":[1,501123],"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<pre class="r"><code># visualize
library(GGally)
nna_covidjoined %&gt;% mutate(cluster = as.factor(pam2$clustering)) %&gt;% 
    ggpairs(columns = c(&quot;Cases&quot;, &quot;Vaccinated&quot;, &quot;Fatalities&quot;), 
        aes(color = cluster))</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-8-3.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code># interpretation of clusters
pam2$silinfo$widths %&gt;% as.data.frame %&gt;% mutate(x = 1221:1) %&gt;% 
    ggplot(aes(x, y = sil_width, fill = as.factor(cluster))) + 
    geom_bar(stat = &quot;identity&quot;) + xlab(&quot;&quot;) + facet_grid(cluster ~ 
    ., scales = &quot;free_y&quot;) + coord_flip() + theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-8-4.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code># goodness-of-fit: 0.94=strong structure found
pam2$silinfo$avg.width</code></pre>
<pre><code>## [1] 0.9373313</code></pre>
<p>The numeric variables <code>Cases</code>, <code>Fatalities</code>, and <code>Vaccinated</code> were all scaled and then used to find the optimal number of clusters, which was determined to be 2 clusters. Using <code>ggplot</code>, the peak <code>sil_width</code> was reached when k=2. After finding the number of clusters to use with PAM, I was able to run PAM and then visualize the three variables in three-dimensional space with <code>plotly</code>. Then, I was able to visualize all of the pairwise combinations of the three variables with <code>GGally</code>. The highest correlation was between <code>Fatalities</code> and <code>Cases</code> with a correlation value of 0.969. Specifically, cluster 2 has a higher correlation (0.943) than cluster 1 (0.852). This high correlation was also similarly illustrated in the correlation heat map, previously shown. Lastly, I was able to interpret the clusters using <code>silinfo$avg.width</code>. The goodness-of-fit was determined to have an average silhouette width of 0.94, which is indicative of a strong structure.</p>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
